### ISSUE TITLE
log admin error: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by mtsuchih** [akamai/cli-eaa#1]
**Description**
I get an error when runnning the command `akamai eaa log admin `

**Command and Log (filtered personal information)**
```
$ akamai eaa log admin -s 1598886000 -e 1598990000 
2020-09-03 14:02:05,039 [ERROR] MainThread Error parsing admin log line: 'NoneType' object has no attribute 'write', content: user@example.com,users,user@example.com,login,login
Traceback (most recent call last):
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/bin/akamai-eaa", line 678, in get_logs
    self._output.write(line.encode("utf8"))
AttributeError: 'NoneType' object has no attribute 'write'
# Start: 08/31/2020 15:00:00 UTC
# End: 09/01/2020 19:53:20 UTC
# Total: 0 event(s)
```

**Comment by bitonio** [comment]
Hi @mtsuchih 

Thanks for reporting the issue, I was able to reproduce the issue and will work on a fix.
I will update this ticket as soon as it is ready.

**Comment by bitonio** [comment]
@mtsuchih please upgrade to 0.2.3 I just release, the fix should got rid of the error you found.
Thanks for using _cli-eaa_!

**Comment by mtsuchih** [comment]
@bitonio I tested 0.2.3 and it works successfully! Thank you very much for your fix.
