### ISSUE TITLE
EAA App deployment

### ISSUE THREAD

**Issue by rahul8172q** [akamai/cli-eaa#14]
I have created an app, updated it but when i am deploying, its says it will but it never happens.

![image](https://user-images.githubusercontent.com/29429076/195834644-fe0907ae-37c5-48dd-a92a-54854fe4e44d.png)

**Comment by bitonio** [comment]
Hi Rahul,

I see the deploy API response is a 200 OK, deployment should have happened.
The cli did the job, something must have happened after the API call.

I'd retry again once and if the problem persists, contact AkaTec with same screenshot showing the API call and the response so they can dig deeper into what happens.

**Comment by rahul8172q** [comment]
Ok. I tried doing that again and again, no success.


Just want to highlight, i am adding access control section with some tags
and then deploying the json. Hope i am not doing anything wrong!



Thanks
Rahul

**Comment by bitonio** [comment]
Closing this issue as the API was responding with 200, the cli handled the response correctly.
If the app is not deployed and API responded 200, I recommend reaching out AkaTec support (you can add a link to this issue).
