### ISSUE TITLE
Connector swap failed with error

### ISSUE THREAD

**Issue by hsato1192** [akamai/cli-eaa#18]
Hi,
I run the command to swap the connector. It was failed with the following error. 
My cli-eaa version is 0.5.6.

`
% akamai eaa  connector con://xxxxxxxx swap --dryrun con://xxxxxxxx
#Operation,connector-id,connector-name,app-id,app-name
2023-02-06 13:50:03,530 root E cli-eaa general exception
Traceback (most recent call last):
  File "/Users/user1/.akamai-cli/src/cli-eaa/bin/akamai-eaa", line 279, in <module>
    c.swap(config.connector_id, config.new_connector_id, config.dryrun)
  File "/Users/user1/.akamai-cli/src/cli-eaa/libeaa/connector.py", line 336, in swap
    for app_using_old_con, app_name, app_host in self.findappbyconnector(old_con):
ValueError: too many values to unpack (expected 3)
`

**Comment by bitonio** [comment]
Hi @hsato1192 -- I'll reproduce the issue in lab and provide a fix.
Give me a couple of days.

**Comment by hsato1192** [comment]
Hi @bitonio I think I fixed the bug in the script and made a pull request. Can you please review and accept if it looks fine.
https://github.com/akamai/cli-eaa/pull/19

**Comment by bitonio** [comment]
PR accepted.
