### ISSUE TITLE
[Documentation] Provide more complete jinja2 examples

### ISSUE THREAD

**Issue by alexkleinfig** [akamai/cli-eaa#36]
Hello,

I am willing to use templates but the documentation is lacking.

I can see here some examples here: https://github.com/akamai/cli-eaa/tree/master/docs/examples, but there is some variables and inclusions are not added to the repository.

For example https://github.com/akamai/cli-eaa/blob/master/docs/examples/webapp.json.j2
"app_profile": {{ AppProfile.HTTP.value }},
    "domain" : {{ AppDomainType.Akamai.value }},
    "name": "EAA CLI Example web Application {{ random_appsuffix }}",
    "description" : "This is a test, feel free to delete this app",
    "host" : "webapp-test-{{ random_appsuffix }}",
    "pop": "{{ cli_cloudzone('US-East') }}",
    "servers": [
        {"origin_host": "10.0.2.3", "orig_tls": "false", "origin_port": 443, "origin_protocol": "https"}
    ],
    "agents": {% include 'includes/akdemo-amer-2maincon.json' %},
    "idp": {% include 'includes/akdemo-idp.json' %},
    "directories": {% include 'includes/akdemo-directory.json' %},
    "groups": {% include 'includes/akdemo-groups-default.json' %}
    
    
I understood i can use variables with akamai eaa app - create --var KEY VALUE -var key value but is there a way to use a var file ?
    
Thank you.

**Comment by bitonio** [comment]
Hi @alexkleinfig 
Right now, the command line doesn't support a var file, that would be a feature request.
In the  meantime you may construct the command line in shell script and then invoke the command.

Tagging this ticket as feat. request.

**Comment by bitonio** [comment]
Also, noted for the example with missing included file, I'll anonymize them this an provide the full set of files.
