### ISSUE TITLE
Create or Modify Application using Akamai Cli

### ISSUE THREAD

**Issue by rahul8172q** [akamai/cli-eaa#8]
I am new to API stuff. I am trying to create an automated call to create an Applicaiton with some set parameters and just  pass Name , connector and destination seperately while making the call.

I saw with POSTMAN, there is a way bit cna anyone help with CLI, is tere any options.

**Comment by bitonio** [comment]
Let's follow up by email it will be easier.
I had some idea about putting together some dedicated documentation around this topic, you give me a good opportunity here.

W.r.t the error, the `cat mynewapp.json.j2` returns an error (very first line, easy to miss)
```
cat: mynewapp.json.j2: No such file or directory
```

Then cli-eaa try to read the input and find nothing, I will add a basic test to have a better error message/handling.

**Comment by bitonio** [comment]
Solved over email.
